services:
  # Main Application
  - type: web
    name: icpscope-dashboard
    env: node
    plan: starter
    buildCommand: npm install --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production