services:
  # Main Application
  - type: web
    name: icpscope-dashboard
    runtime: node
    plan: starter
    buildCommand: npm install --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production