services:
  # Main Application
  - type: web
    name: icpscope-dashboard
    env: node
    plan: starter
    buildCommand: npm install --only=production
    startCommand: node render-deploy.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000